# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Restaurant.create([{ name: 'Le First, restaurant boudoir Paris'},
                   { description: "LIEU D’EXCEPTION - C'est entre la place Vendôme et le jardin des Tuileries que le restaurant Le First a élu domicile. Le célèbre décorateur, Jacques Garcia, en a fait un espace contemporain tendance baroque, où règne une atmosphère cosy et intime qui se prête aussi bien aux tablées conviviales qu'aux dîners romantiques. ASSIETTES MALICIEUSES - Le Chef, Gilles Grasteau, propose une carte inventive, revisitant savamment la cuisine classique, avec une pointe d'audace et de modernité. Il vous suggère notamment le foie gras de canard en raviole, la soupe de poisson glacée au safran, le bar entier de nos côtes farcies (à partager à deux) ou encore en dessert le calisson thym/citron pain de gênes, crème glacée. BIEN-ÊTRE & VOLUPTÉ - Tous les jours, sauf le dimanche, profitez du service voiturier. Une excellente adresse à Paris, d'où vous ressortirez conquis tant par la cuisine que par l’accueil de qualité. Un bon moment en perspective, dont vous vous souviendrez."},
                   { photo_url: 'http://uploads.lafourchette.com/restaurant_photos/247/1247/169/612/le-first-restaurant-boudoir-paris-detail-plat-0e8d2.jpg'}])

Restaurant.create([{ name: 'Mood'},
                   { description: "LIEU D’EXCEPTION - C'est entre la place Vendôme et le jardin des Tuileries que le restaurant Le First a élu domicile. Le célèbre décorateur, Jacques Garcia, en a fait un espace contemporain tendance baroque, où règne une atmosphère cosy et intime qui se prête aussi bien aux tablées conviviales qu'aux dîners romantiques. ASSIETTES MALICIEUSES - Le Chef, Gilles Grasteau, propose une carte inventive, revisitant savamment la cuisine classique, avec une pointe d'audace et de modernité. Il vous suggère notamment le foie gras de canard en raviole, la soupe de poisson glacée au safran, le bar entier de nos côtes farcies (à partager à deux) ou encore en dessert le calisson thym/citron pain de gênes, crème glacée. BIEN-ÊTRE & VOLUPTÉ - Tous les jours, sauf le dimanche, profitez du service voiturier. Une excellente adresse à Paris, d'où vous ressortirez conquis tant par la cuisine que par l’accueil de qualité. Un bon moment en perspective, dont vous vous souviendrez."},
                   { photo_url: 'http://uploads.lafourchette.com/restaurant_photos/530/2530/169/612/Apercu-de-l-interieur.jpg'}])

Restaurant.create([{ name: 'Goumard'},
                   { description: "LIEU D’EXCEPTION - C'est entre la place Vendôme et le jardin des Tuileries que le restaurant Le First a élu domicile. Le célèbre décorateur, Jacques Garcia, en a fait un espace contemporain tendance baroque, où règne une atmosphère cosy et intime qui se prête aussi bien aux tablées conviviales qu'aux dîners romantiques. ASSIETTES MALICIEUSES - Le Chef, Gilles Grasteau, propose une carte inventive, revisitant savamment la cuisine classique, avec une pointe d'audace et de modernité. Il vous suggère notamment le foie gras de canard en raviole, la soupe de poisson glacée au safran, le bar entier de nos côtes farcies (à partager à deux) ou encore en dessert le calisson thym/citron pain de gênes, crème glacée. BIEN-ÊTRE & VOLUPTÉ - Tous les jours, sauf le dimanche, profitez du service voiturier. Une excellente adresse à Paris, d'où vous ressortirez conquis tant par la cuisine que par l’accueil de qualité. Un bon moment en perspective, dont vous vous souviendrez."},
                   { photo_url: 'http://uploads.lafourchette.com/restaurant_photos/884/1884/169/612/Detail-de-la-table.jpg'}])

Restaurant.create([{ name: 'Pietro'},
                   { description: "LIEU D’EXCEPTION - C'est entre la place Vendôme et le jardin des Tuileries que le restaurant Le First a élu domicile. Le célèbre décorateur, Jacques Garcia, en a fait un espace contemporain tendance baroque, où règne une atmosphère cosy et intime qui se prête aussi bien aux tablées conviviales qu'aux dîners romantiques. ASSIETTES MALICIEUSES - Le Chef, Gilles Grasteau, propose une carte inventive, revisitant savamment la cuisine classique, avec une pointe d'audace et de modernité. Il vous suggère notamment le foie gras de canard en raviole, la soupe de poisson glacée au safran, le bar entier de nos côtes farcies (à partager à deux) ou encore en dessert le calisson thym/citron pain de gênes, crème glacée. BIEN-ÊTRE & VOLUPTÉ - Tous les jours, sauf le dimanche, profitez du service voiturier. Une excellente adresse à Paris, d'où vous ressortirez conquis tant par la cuisine que par l’accueil de qualité. Un bon moment en perspective, dont vous vous souviendrez."},
                   { photo_url: 'http://uploads.lafourchette.com/restaurant_photos/310/19310/169/612/a6d98f26b71f0d0461e8d6c2d140924f.jpg'}])

Restaurant.create([{ name: 'Toi'},
                   { description: "LIEU D’EXCEPTION - C'est entre la place Vendôme et le jardin des Tuileries que le restaurant Le First a élu domicile. Le célèbre décorateur, Jacques Garcia, en a fait un espace contemporain tendance baroque, où règne une atmosphère cosy et intime qui se prête aussi bien aux tablées conviviales qu'aux dîners romantiques. ASSIETTES MALICIEUSES - Le Chef, Gilles Grasteau, propose une carte inventive, revisitant savamment la cuisine classique, avec une pointe d'audace et de modernité. Il vous suggère notamment le foie gras de canard en raviole, la soupe de poisson glacée au safran, le bar entier de nos côtes farcies (à partager à deux) ou encore en dessert le calisson thym/citron pain de gênes, crème glacée. BIEN-ÊTRE & VOLUPTÉ - Tous les jours, sauf le dimanche, profitez du service voiturier. Une excellente adresse à Paris, d'où vous ressortirez conquis tant par la cuisine que par l’accueil de qualité. Un bon moment en perspective, dont vous vous souviendrez."},
                   { photo_url: 'http://uploads.lafourchette.com/restaurant_photos/794/1794/169/612/toi-belle-piece-de-boeuf-et-sa-sauce-bearnaise-aea5f.jpg'}])
